[project]
name = "mcp-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "databricks>=0.2",
    "databricks-sql-connector>=4.0.3",
    "dotenv>=0.9.9",
    "mcp[cli]>=1.9.1",
    "polars>=1.30.0",
]
